version: "3.3"
services:
    nginx:
        image: nginx:1.20.0
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src/main/resources/static/:/var/www/static/
        restart: unless-stopped
        ports:
            - 81:81
        networks:
            - run-env2
        

    #memcached

    app-ted:
        image: ted-search
        container_name: "app-ted"
        ports: 
            - 9191:9191
        networks: 
            - run-env2
    
    
networks: 
    run-env2:


